### ISSUE TITLE
Public GeyserConnect server resource leaks

### ISSUE THREAD

**Issue by Greaper88** [GeyserMC/GeyserConnect#16]
Myself and EasyClifton are in charge of the public GeyserConnect. 
The instance has 4000 MB of RAM assigned, and the machine has 8 3.2 GHz Xeon cores. 
After a period of just 24 hours, i noticed that he server sounded really loud. Checking the Pterodactyl panel I use to manage it, I saw thatthe assigned RAM was fully taken, and that CPU usage was pegged at 800%, 100% being 1 CPU core. I checked htop directly on the machine, and it confirmed a fully pegged CPU on all cores.
This would appear to point to some sort of memory leak, but not sure what the issue is.

**Comment by rtm516** [comment]
Maybe fixed by https://github.com/GeyserMC/GeyserConnect/commit/f014ca4ef833153156234140b474fef9cd3748fc
Needs confirming

**Comment by Greaper88** [comment]
32 hours of checking in on the server at this point revealed max RAM consumption of 1.6GBm and max observed CPU usage of 60%.

**Comment by Greaper88** [comment]
![Screenshot_20201210-234213_Firefox](https://user-images.githubusercontent.com/61922763/101882694-d960e200-3b5b-11eb-9b66-8ac348125852.jpg)
![Screenshot_20201210-234207_Firefox](https://user-images.githubusercontent.com/61922763/101882698-d9f97880-3b5b-11eb-8731-6629fd1aa9b5.jpg)


Issue still exists. But it is not nearly as bad as before https://github.com/GeyserMC/GeyserConnect/commit/f014ca4ef833153156234140b474fef9cd3748fc
It would seem that was only one of other possible issues.

**Comment by bundabrg** [comment]
How busy is this? Like how many players etc. Does it happen if the server doesn't have anyone connect through the day?

**Comment by Greaper88** [comment]
I'm honestly not certain, but the console is constantly scrolling. We started this at the end of August, and have had over 8,000 unique users. I'm certain there several hundred a day on some days.

**Comment by bundabrg** [comment]
Ahh well you are probably in the best position to test since my servers are far more quieter so the problem may simply not manifest itself. I think we'll just work out some way of debugging this and get back in this thread. Maybe for now cronjob a daily restart of the service.

**Comment by JohnB17** [comment]
Whats the ip of this public geyserconnect?

**Comment by rtm516** [comment]
Is this still an issue? or has it been sorted now?

**Comment by rtm516** [comment]
Closing due to inactivity
